# Configurações de build para um projeto Vite
[build]
  command = "npm run build"
  publish = "dist"

# Regra de redirecionamento para Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200